#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CalculatorApp.Resource", IsApplication=true)]

namespace CalculatorApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryLight = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorPrimaryText = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int colorSecondaryText = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int colorText = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int ic_launcher_background = 2130771975;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int addButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int answerTextView = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int billTotalText = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int divButton = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int firstNumberEditText = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int linearLayout2 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int mulButton = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int secondNumberEditText = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int subButton = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int subTotalEditText = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int textView1 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int tipCalcButton = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int tipSeekBar = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int tipTotalText = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int tipViewText = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int toCalcButton = 2130837519;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int calculator_layout = 2130903042;
			
			// aapt resource value: 0x7F030000
			public const int TipCalc_Layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher_foreground = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_round = 2130968578;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int add_button = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ans_text = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int div_button = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int mul_button = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int sub_button = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int bigFontStyle = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int customTheme = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
